# -*- coding: utf-8 -*-
from odoo import fields, models


class StockPicking(models.Model):
    _inherit = 'stock.picking'

    stock_conversion_id = fields.Many2one(
        'stock.conversion', string='Stock Conversion', readonly=True, copy=False,
        index=True,
        help='Set when this transfer was generated by a Stock Conversion / '
             'Pack & Convert record to move finished goods out of the '
             'virtual Production location into their destination.',
    )
